nelmio_api_doc:
  documentation:
    info:
      title: Ergonode
    securityDefinitions:
      api_key:
        type: apiKey
        description: Your Json Web Token (Bearer {TOKEN})
        name: '%authorization_header%'
        in: header
    security:
      -   api_key: []
  areas:
    path_patterns:
      - ^/api(?!/doc$)
