nelmio_api_doc:
  documentation:
    info:
      title: Ergonode
      version: 1.0.0-beta.3
    securityDefinitions:
      api_key:
        type: apiKey
        description: Your Json Web Token (Bearer {TOKEN})
        name: JWTAuthorization
        in: header
    security:
      -   api_key: []
  areas:
    path_patterns:
      - ^/api(?!/doc$)
